name: Build and deploy

on:
    push:
        branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - uses: actions/checkout@v4

            - name: Prepare environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install deps
              run: npm ci

            - name: Build plugin(s)
              run: npm run build

            - name: Copy additional files
              run: |
                  cp README.md dist/README.md
                  printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
                  printf -- "> **Note:** You accessed a link that returned a 404. For Bunny, copy the plugin URL ending in \`/dislate/\` and add it as a plugin source.\n\n" >> dist/404.md
                  cat README.md >> dist/404.md

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
